apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dcp-eval-secretmode-2
  description: Python 3.11 microservice created via the DCP Golden Path
  tags:
    - python
    - microservice
  annotations:
    github.com/project-slug: hingerabhinav/dcp-eval-secretmode-2
spec:
  type: service
  lifecycle: experimental
  owner: harness
